[project]
name = "autogen-101"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-agentchat>=0.5.7",
    "autogen-ext[mcp,ollama]>=0.5.7",
    "mcp[cli]>=1.9.2",
]
